### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ufiano** [Mashopy/Mashopy#1]
Do you discord or telegram?

**Comment by Mashopy** [comment]
Why

**Comment by Ufiano** [comment]
https://github.com/Mashopy/realmeC31_C35_narzo50A-Prime-AndroidR-kernel-source

**Comment by Mashopy** [comment]
?

**Comment by Ufiano** [comment]
I want to create common tree

**Comment by Mashopy** [comment]
I don't see how that regard me ?
